name: SOLOFloatTag
version: "0.0.1"
api: [1.0.0]
author: solo
main: solo.solofloattag.Main
load: POSTWORLD
commands:
  태그:
    usage: /태그 [내용...]
    description: 태그 추가 명령어
    permission: solofloattag.command.tag

permissions:
  solofloattag:
    children:
      solofloattag.command:
        children:
          solofloattag.command.tag:
            default: op